openapi: 3.0.2
info:
  title: 'OAuth2 API'
  version: "1.0.0"
paths:
  /authentication/register/:
     post:
      summary: Register
      description: Register - registers user to the server
      operationId: Register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  pattern: '^(?=.{8,150}$)[a-zA-Z0-9\w.@+\-]$'
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: kitsQjmub3OgdvIHcr5dxJnzYm2MBP
                  expires_in:
                    type: integer
                    example: 36000
                  token_type:
                    type: string
                    example: Bearer
                  scope:
                    type: string
                    example: read write
                  refresh_token:
                    type: string
                    example: faDaErE61FG4krPdLqKuleinxocYwS
        '400':
          description: Username already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: array
                    items:
                     type: string
                     example: A user with that username already exists.
  /authentication/token/:
    post:
      summary: Login
      description: Login - get tokens with username and password
      operationId: Login
      requestBody:
        required: true
        content:
          application/json:
             schema:
               type: object
               properties:
                  username:
                    type: string
                    pattern: '^(?=.{8,150}$)[a-zA-Z0-9\w.@+\-]$'
                  password:
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: kitsQjmub3OgdvIHcr5dxJnzYm2MBP
                  expires_in:
                    type: integer
                    example: 36000
                  token_type:
                    type: string
                    example: Bearer
                  scope:
                    type: string
                    example: read write
                  refresh_token:
                    type: string
                    example: faDaErE61FG4krPdLqKuleinxocYwS
  /authentication/token/refresh/:
    post:
      summary: Refresh
      description: Get refresh-token for long-term access
      operationId: Refresh
      requestBody:
        required: true
        content:
          application/json:
             schema:
               type: object
               properties:
                  refresh_token:
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: kitsQjmub3OgdvIHcr5dxJnzYm2MBP
                  expires_in:
                    type: integer
                    example: 36000
                  token_type:
                    type: string
                    example: Bearer
                  scope:
                    type: string
                    example: read write
                  refresh_token:
                    type: string
                    example: faDaErE61FG4krPdLqKuleinxocYwS
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid_grant
  /authentication/token/revoke/:
    post:
      summary: Revoke
      description: Logout - revoke tokens
      operationId: Revoke
      requestBody:
        required: true
        content:
          application/json:
             schema:
               type: object
               properties:
                  token:
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: token revoked
servers:
- url: https://secret-plateau-34662.herokuapp.com
  description: OAuth2 API